#!/usr/bin/env python3
import parse
parse.table = {
        '\x19 ::=  ● exp \x18': {
                'IFF': None ,
                'IF': None ,
                'OR': None ,
                'XOR': None ,
                'AND': None ,
                'NOT': 'e ::= NOT ● f',
                'EXISTS': 'f ::= EXISTS ● PROP term',
                'PROP': 'term ::= PROP ● ',
                'FORALL': 'f ::= FORALL ● PROP term',
                'LPAREN': 'term ::= LPAREN ● exp RPAREN',
                'RPAREN': None ,
                'BOOL': 'term ::= BOOL ● ',
                '\x18': None ,
                'exp': '\x19 ::= exp ● \x18',
                'a': 'exp ::= a ● ',
                'b': 'a ::= b ● ',
                'c': 'b ::= c ● ',
                'd': 'c ::= d ● ',
                'e': 'd ::= e ● ',
                'f': 'e ::= f ● ',
                'term': 'exp ::= term ● IFF a',
                '\x19': None ,
        },
        '\x19 ::= exp ● \x18': {
                'IFF': None ,
                'IF': None ,
                'OR': None ,
                'XOR': None ,
                'AND': None ,
                'NOT': None ,
                'EXISTS': None ,
                'PROP': None ,
                'FORALL': None ,
                'LPAREN': None ,
                'RPAREN': None ,
                'BOOL': None ,
                '\x18': 'accept',
                'exp': None ,
                'a': None ,
                'b': None ,
                'c': None ,
                'd': None ,
                'e': None ,
                'f': None ,
                'term': None ,
                '\x19': None ,
        },
        'exp ::= a ● ': {
                'IFF': None ,
                'IF': None ,
                'OR': None ,
                'XOR': None ,
                'AND': None ,
                'NOT': None ,
                'EXISTS': None ,
                'PROP': None ,
                'FORALL': None ,
                'LPAREN': None ,
                'RPAREN': ('exp', 1) ,
                'BOOL': None ,
                '\x18': ('exp', 1) ,
                'exp': None ,
                'a': None ,
                'b': None ,
                'c': None ,
                'd': None ,
                'e': None ,
                'f': None ,
                'term': None ,
                '\x19': None ,
        },
        'a ::= b ● ': {
                'IFF': None ,
                'IF': None ,
                'OR': None ,
                'XOR': None ,
                'AND': None ,
                'NOT': None ,
                'EXISTS': None ,
                'PROP': None ,
                'FORALL': None ,
                'LPAREN': None ,
                'RPAREN': ('a', 1) ,
                'BOOL': None ,
                '\x18': ('a', 1) ,
                'exp': None ,
                'a': None ,
                'b': None ,
                'c': None ,
                'd': None ,
                'e': None ,
                'f': None ,
                'term': None ,
                '\x19': None ,
        },
        'b ::= c ● ': {
                'IFF': None ,
                'IF': None ,
                'OR': None ,
                'XOR': None ,
                'AND': None ,
                'NOT': None ,
                'EXISTS': None ,
                'PROP': None ,
                'FORALL': None ,
                'LPAREN': None ,
                'RPAREN': ('b', 1) ,
                'BOOL': None ,
                '\x18': ('b', 1) ,
                'exp': None ,
                'a': None ,
                'b': None ,
                'c': None ,
                'd': None ,
                'e': None ,
                'f': None ,
                'term': None ,
                '\x19': None ,
        },
        'c ::= d ● ': {
                'IFF': None ,
                'IF': None ,
                'OR': None ,
                'XOR': None ,
                'AND': None ,
                'NOT': None ,
                'EXISTS': None ,
                'PROP': None ,
                'FORALL': None ,
                'LPAREN': None ,
                'RPAREN': ('c', 1) ,
                'BOOL': None ,
                '\x18': ('c', 1) ,
                'exp': None ,
                'a': None ,
                'b': None ,
                'c': None ,
                'd': None ,
                'e': None ,
                'f': None ,
                'term': None ,
                '\x19': None ,
        },
        'd ::= e ● ': {
                'IFF': None ,
                'IF': None ,
                'OR': None ,
                'XOR': None ,
                'AND': None ,
                'NOT': None ,
                'EXISTS': None ,
                'PROP': None ,
                'FORALL': None ,
                'LPAREN': None ,
                'RPAREN': ('d', 1) ,
                'BOOL': None ,
                '\x18': ('d', 1) ,
                'exp': None ,
                'a': None ,
                'b': None ,
                'c': None ,
                'd': None ,
                'e': None ,
                'f': None ,
                'term': None ,
                '\x19': None ,
        },
        'e ::= f ● ': {
                'IFF': None ,
                'IF': None ,
                'OR': None ,
                'XOR': None ,
                'AND': None ,
                'NOT': None ,
                'EXISTS': None ,
                'PROP': None ,
                'FORALL': None ,
                'LPAREN': None ,
                'RPAREN': ('e', 1) ,
                'BOOL': None ,
                '\x18': ('e', 1) ,
                'exp': None ,
                'a': None ,
                'b': None ,
                'c': None ,
                'd': None ,
                'e': None ,
                'f': None ,
                'term': None ,
                '\x19': None ,
        },
        'exp ::= term ● IFF a': {
                'IFF': 'exp ::= term IFF ● a',
                'IF': 'a ::= term IF ● b',
                'OR': 'b ::= term OR ● c',
                'XOR': 'c ::= term XOR ● d',
                'AND': 'd ::= term AND ● e',
                'NOT': None ,
                'EXISTS': None ,
                'PROP': None ,
                'FORALL': None ,
                'LPAREN': None ,
                'RPAREN': ('f', 1) ,
                'BOOL': None ,
                '\x18': ('f', 1) ,
                'exp': None ,
                'a': None ,
                'b': None ,
                'c': None ,
                'd': None ,
                'e': None ,
                'f': None ,
                'term': None ,
                '\x19': None ,
        },
        'exp ::= term IFF ● a': {
                'IFF': None ,
                'IF': None ,
                'OR': None ,
                'XOR': None ,
                'AND': None ,
                'NOT': 'e ::= NOT ● f',
                'EXISTS': 'f ::= EXISTS ● PROP term',
                'PROP': 'term ::= PROP ● ',
                'FORALL': 'f ::= FORALL ● PROP term',
                'LPAREN': 'term ::= LPAREN ● exp RPAREN',
                'RPAREN': None ,
                'BOOL': 'term ::= BOOL ● ',
                '\x18': None ,
                'exp': None ,
                'a': 'exp ::= term IFF a ● ',
                'b': 'a ::= b ● ',
                'c': 'b ::= c ● ',
                'd': 'c ::= d ● ',
                'e': 'd ::= e ● ',
                'f': 'e ::= f ● ',
                'term': 'a ::= term ● IF b',
                '\x19': None ,
        },
        'exp ::= term IFF a ● ': {
                'IFF': None ,
                'IF': None ,
                'OR': None ,
                'XOR': None ,
                'AND': None ,
                'NOT': None ,
                'EXISTS': None ,
                'PROP': None ,
                'FORALL': None ,
                'LPAREN': None ,
                'RPAREN': ('exp', 3) ,
                'BOOL': None ,
                '\x18': ('exp', 3) ,
                'exp': None ,
                'a': None ,
                'b': None ,
                'c': None ,
                'd': None ,
                'e': None ,
                'f': None ,
                'term': None ,
                '\x19': None ,
        },
        'a ::= term ● IF b': {
                'IFF': None ,
                'IF': 'a ::= term IF ● b',
                'OR': 'b ::= term OR ● c',
                'XOR': 'c ::= term XOR ● d',
                'AND': 'd ::= term AND ● e',
                'NOT': None ,
                'EXISTS': None ,
                'PROP': None ,
                'FORALL': None ,
                'LPAREN': None ,
                'RPAREN': ('f', 1) ,
                'BOOL': None ,
                '\x18': ('f', 1) ,
                'exp': None ,
                'a': None ,
                'b': None ,
                'c': None ,
                'd': None ,
                'e': None ,
                'f': None ,
                'term': None ,
                '\x19': None ,
        },
        'a ::= term IF ● b': {
                'IFF': None ,
                'IF': None ,
                'OR': None ,
                'XOR': None ,
                'AND': None ,
                'NOT': 'e ::= NOT ● f',
                'EXISTS': 'f ::= EXISTS ● PROP term',
                'PROP': 'term ::= PROP ● ',
                'FORALL': 'f ::= FORALL ● PROP term',
                'LPAREN': 'term ::= LPAREN ● exp RPAREN',
                'RPAREN': None ,
                'BOOL': 'term ::= BOOL ● ',
                '\x18': None ,
                'exp': None ,
                'a': None ,
                'b': 'a ::= term IF b ● ',
                'c': 'b ::= c ● ',
                'd': 'c ::= d ● ',
                'e': 'd ::= e ● ',
                'f': 'e ::= f ● ',
                'term': 'b ::= term ● OR c',
                '\x19': None ,
        },
        'a ::= term IF b ● ': {
                'IFF': None ,
                'IF': None ,
                'OR': None ,
                'XOR': None ,
                'AND': None ,
                'NOT': None ,
                'EXISTS': None ,
                'PROP': None ,
                'FORALL': None ,
                'LPAREN': None ,
                'RPAREN': ('a', 3) ,
                'BOOL': None ,
                '\x18': ('a', 3) ,
                'exp': None ,
                'a': None ,
                'b': None ,
                'c': None ,
                'd': None ,
                'e': None ,
                'f': None ,
                'term': None ,
                '\x19': None ,
        },
        'b ::= term ● OR c': {
                'IFF': None ,
                'IF': None ,
                'OR': 'b ::= term OR ● c',
                'XOR': 'c ::= term XOR ● d',
                'AND': 'd ::= term AND ● e',
                'NOT': None ,
                'EXISTS': None ,
                'PROP': None ,
                'FORALL': None ,
                'LPAREN': None ,
                'RPAREN': ('f', 1) ,
                'BOOL': None ,
                '\x18': ('f', 1) ,
                'exp': None ,
                'a': None ,
                'b': None ,
                'c': None ,
                'd': None ,
                'e': None ,
                'f': None ,
                'term': None ,
                '\x19': None ,
        },
        'b ::= term OR ● c': {
                'IFF': None ,
                'IF': None ,
                'OR': None ,
                'XOR': None ,
                'AND': None ,
                'NOT': 'e ::= NOT ● f',
                'EXISTS': 'f ::= EXISTS ● PROP term',
                'PROP': 'term ::= PROP ● ',
                'FORALL': 'f ::= FORALL ● PROP term',
                'LPAREN': 'term ::= LPAREN ● exp RPAREN',
                'RPAREN': None ,
                'BOOL': 'term ::= BOOL ● ',
                '\x18': None ,
                'exp': None ,
                'a': None ,
                'b': None ,
                'c': 'b ::= term OR c ● ',
                'd': 'c ::= d ● ',
                'e': 'd ::= e ● ',
                'f': 'e ::= f ● ',
                'term': 'c ::= term ● XOR d',
                '\x19': None ,
        },
        'b ::= term OR c ● ': {
                'IFF': None ,
                'IF': None ,
                'OR': None ,
                'XOR': None ,
                'AND': None ,
                'NOT': None ,
                'EXISTS': None ,
                'PROP': None ,
                'FORALL': None ,
                'LPAREN': None ,
                'RPAREN': ('b', 3) ,
                'BOOL': None ,
                '\x18': ('b', 3) ,
                'exp': None ,
                'a': None ,
                'b': None ,
                'c': None ,
                'd': None ,
                'e': None ,
                'f': None ,
                'term': None ,
                '\x19': None ,
        },
        'c ::= term ● XOR d': {
                'IFF': None ,
                'IF': None ,
                'OR': None ,
                'XOR': 'c ::= term XOR ● d',
                'AND': 'd ::= term AND ● e',
                'NOT': None ,
                'EXISTS': None ,
                'PROP': None ,
                'FORALL': None ,
                'LPAREN': None ,
                'RPAREN': ('f', 1) ,
                'BOOL': None ,
                '\x18': ('f', 1) ,
                'exp': None ,
                'a': None ,
                'b': None ,
                'c': None ,
                'd': None ,
                'e': None ,
                'f': None ,
                'term': None ,
                '\x19': None ,
        },
        'c ::= term XOR ● d': {
                'IFF': None ,
                'IF': None ,
                'OR': None ,
                'XOR': None ,
                'AND': None ,
                'NOT': 'e ::= NOT ● f',
                'EXISTS': 'f ::= EXISTS ● PROP term',
                'PROP': 'term ::= PROP ● ',
                'FORALL': 'f ::= FORALL ● PROP term',
                'LPAREN': 'term ::= LPAREN ● exp RPAREN',
                'RPAREN': None ,
                'BOOL': 'term ::= BOOL ● ',
                '\x18': None ,
                'exp': None ,
                'a': None ,
                'b': None ,
                'c': None ,
                'd': 'c ::= term XOR d ● ',
                'e': 'd ::= e ● ',
                'f': 'e ::= f ● ',
                'term': 'd ::= term ● AND e',
                '\x19': None ,
        },
        'c ::= term XOR d ● ': {
                'IFF': None ,
                'IF': None ,
                'OR': None ,
                'XOR': None ,
                'AND': None ,
                'NOT': None ,
                'EXISTS': None ,
                'PROP': None ,
                'FORALL': None ,
                'LPAREN': None ,
                'RPAREN': ('c', 3) ,
                'BOOL': None ,
                '\x18': ('c', 3) ,
                'exp': None ,
                'a': None ,
                'b': None ,
                'c': None ,
                'd': None ,
                'e': None ,
                'f': None ,
                'term': None ,
                '\x19': None ,
        },
        'd ::= term ● AND e': {
                'IFF': None ,
                'IF': None ,
                'OR': None ,
                'XOR': None ,
                'AND': 'd ::= term AND ● e',
                'NOT': None ,
                'EXISTS': None ,
                'PROP': None ,
                'FORALL': None ,
                'LPAREN': None ,
                'RPAREN': ('f', 1) ,
                'BOOL': None ,
                '\x18': ('f', 1) ,
                'exp': None ,
                'a': None ,
                'b': None ,
                'c': None ,
                'd': None ,
                'e': None ,
                'f': None ,
                'term': None ,
                '\x19': None ,
        },
        'd ::= term AND ● e': {
                'IFF': None ,
                'IF': None ,
                'OR': None ,
                'XOR': None ,
                'AND': None ,
                'NOT': 'e ::= NOT ● f',
                'EXISTS': 'f ::= EXISTS ● PROP term',
                'PROP': 'term ::= PROP ● ',
                'FORALL': 'f ::= FORALL ● PROP term',
                'LPAREN': 'term ::= LPAREN ● exp RPAREN',
                'RPAREN': None ,
                'BOOL': 'term ::= BOOL ● ',
                '\x18': None ,
                'exp': None ,
                'a': None ,
                'b': None ,
                'c': None ,
                'd': None ,
                'e': 'd ::= term AND e ● ',
                'f': 'e ::= f ● ',
                'term': 'f ::= term ● ',
                '\x19': None ,
        },
        'd ::= term AND e ● ': {
                'IFF': None ,
                'IF': None ,
                'OR': None ,
                'XOR': None ,
                'AND': None ,
                'NOT': None ,
                'EXISTS': None ,
                'PROP': None ,
                'FORALL': None ,
                'LPAREN': None ,
                'RPAREN': ('d', 3) ,
                'BOOL': None ,
                '\x18': ('d', 3) ,
                'exp': None ,
                'a': None ,
                'b': None ,
                'c': None ,
                'd': None ,
                'e': None ,
                'f': None ,
                'term': None ,
                '\x19': None ,
        },
        'f ::= term ● ': {
                'IFF': None ,
                'IF': None ,
                'OR': None ,
                'XOR': None ,
                'AND': None ,
                'NOT': None ,
                'EXISTS': None ,
                'PROP': None ,
                'FORALL': None ,
                'LPAREN': None ,
                'RPAREN': ('f', 1) ,
                'BOOL': None ,
                '\x18': ('f', 1) ,
                'exp': None ,
                'a': None ,
                'b': None ,
                'c': None ,
                'd': None ,
                'e': None ,
                'f': None ,
                'term': None ,
                '\x19': None ,
        },
        'e ::= NOT ● f': {
                'IFF': None ,
                'IF': None ,
                'OR': None ,
                'XOR': None ,
                'AND': None ,
                'NOT': None ,
                'EXISTS': 'f ::= EXISTS ● PROP term',
                'PROP': 'term ::= PROP ● ',
                'FORALL': 'f ::= FORALL ● PROP term',
                'LPAREN': 'term ::= LPAREN ● exp RPAREN',
                'RPAREN': None ,
                'BOOL': 'term ::= BOOL ● ',
                '\x18': None ,
                'exp': None ,
                'a': None ,
                'b': None ,
                'c': None ,
                'd': None ,
                'e': None ,
                'f': 'e ::= NOT f ● ',
                'term': 'f ::= term ● ',
                '\x19': None ,
        },
        'e ::= NOT f ● ': {
                'IFF': None ,
                'IF': None ,
                'OR': None ,
                'XOR': None ,
                'AND': None ,
                'NOT': None ,
                'EXISTS': None ,
                'PROP': None ,
                'FORALL': None ,
                'LPAREN': None ,
                'RPAREN': ('e', 2) ,
                'BOOL': None ,
                '\x18': ('e', 2) ,
                'exp': None ,
                'a': None ,
                'b': None ,
                'c': None ,
                'd': None ,
                'e': None ,
                'f': None ,
                'term': None ,
                '\x19': None ,
        },
        'f ::= EXISTS ● PROP term': {
                'IFF': None ,
                'IF': None ,
                'OR': None ,
                'XOR': None ,
                'AND': None ,
                'NOT': None ,
                'EXISTS': None ,
                'PROP': 'f ::= EXISTS PROP ● term',
                'FORALL': None ,
                'LPAREN': None ,
                'RPAREN': None ,
                'BOOL': None ,
                '\x18': None ,
                'exp': None ,
                'a': None ,
                'b': None ,
                'c': None ,
                'd': None ,
                'e': None ,
                'f': None ,
                'term': None ,
                '\x19': None ,
        },
        'f ::= EXISTS PROP ● term': {
                'IFF': None ,
                'IF': None ,
                'OR': None ,
                'XOR': None ,
                'AND': None ,
                'NOT': None ,
                'EXISTS': None ,
                'PROP': 'term ::= PROP ● ',
                'FORALL': None ,
                'LPAREN': 'term ::= LPAREN ● exp RPAREN',
                'RPAREN': None ,
                'BOOL': 'term ::= BOOL ● ',
                '\x18': None ,
                'exp': None ,
                'a': None ,
                'b': None ,
                'c': None ,
                'd': None ,
                'e': None ,
                'f': None ,
                'term': 'f ::= EXISTS PROP term ● ',
                '\x19': None ,
        },
        'f ::= EXISTS PROP term ● ': {
                'IFF': None ,
                'IF': None ,
                'OR': None ,
                'XOR': None ,
                'AND': None ,
                'NOT': None ,
                'EXISTS': None ,
                'PROP': None ,
                'FORALL': None ,
                'LPAREN': None ,
                'RPAREN': ('f', 3) ,
                'BOOL': None ,
                '\x18': ('f', 3) ,
                'exp': None ,
                'a': None ,
                'b': None ,
                'c': None ,
                'd': None ,
                'e': None ,
                'f': None ,
                'term': None ,
                '\x19': None ,
        },
        'term ::= PROP ● ': {
                'IFF': ('term', 1) ,
                'IF': ('term', 1) ,
                'OR': ('term', 1) ,
                'XOR': ('term', 1) ,
                'AND': ('term', 1) ,
                'NOT': None ,
                'EXISTS': None ,
                'PROP': None ,
                'FORALL': None ,
                'LPAREN': None ,
                'RPAREN': ('term', 1) ,
                'BOOL': None ,
                '\x18': ('term', 1) ,
                'exp': None ,
                'a': None ,
                'b': None ,
                'c': None ,
                'd': None ,
                'e': None ,
                'f': None ,
                'term': None ,
                '\x19': None ,
        },
        'term ::= LPAREN ● exp RPAREN': {
                'IFF': None ,
                'IF': None ,
                'OR': None ,
                'XOR': None ,
                'AND': None ,
                'NOT': 'e ::= NOT ● f',
                'EXISTS': 'f ::= EXISTS ● PROP term',
                'PROP': 'term ::= PROP ● ',
                'FORALL': 'f ::= FORALL ● PROP term',
                'LPAREN': 'term ::= LPAREN ● exp RPAREN',
                'RPAREN': None ,
                'BOOL': 'term ::= BOOL ● ',
                '\x18': None ,
                'exp': 'term ::= LPAREN exp ● RPAREN',
                'a': 'exp ::= a ● ',
                'b': 'a ::= b ● ',
                'c': 'b ::= c ● ',
                'd': 'c ::= d ● ',
                'e': 'd ::= e ● ',
                'f': 'e ::= f ● ',
                'term': 'exp ::= term ● IFF a',
                '\x19': None ,
        },
        'term ::= LPAREN exp ● RPAREN': {
                'IFF': None ,
                'IF': None ,
                'OR': None ,
                'XOR': None ,
                'AND': None ,
                'NOT': None ,
                'EXISTS': None ,
                'PROP': None ,
                'FORALL': None ,
                'LPAREN': None ,
                'RPAREN': 'term ::= LPAREN exp RPAREN ● ',
                'BOOL': None ,
                '\x18': None ,
                'exp': None ,
                'a': None ,
                'b': None ,
                'c': None ,
                'd': None ,
                'e': None ,
                'f': None ,
                'term': None ,
                '\x19': None ,
        },
        'term ::= LPAREN exp RPAREN ● ': {
                'IFF': ('term', 3) ,
                'IF': ('term', 3) ,
                'OR': ('term', 3) ,
                'XOR': ('term', 3) ,
                'AND': ('term', 3) ,
                'NOT': None ,
                'EXISTS': None ,
                'PROP': None ,
                'FORALL': None ,
                'LPAREN': None ,
                'RPAREN': ('term', 3) ,
                'BOOL': None ,
                '\x18': ('term', 3) ,
                'exp': None ,
                'a': None ,
                'b': None ,
                'c': None ,
                'd': None ,
                'e': None ,
                'f': None ,
                'term': None ,
                '\x19': None ,
        },
        'f ::= FORALL ● PROP term': {
                'IFF': None ,
                'IF': None ,
                'OR': None ,
                'XOR': None ,
                'AND': None ,
                'NOT': None ,
                'EXISTS': None ,
                'PROP': 'f ::= FORALL PROP ● term',
                'FORALL': None ,
                'LPAREN': None ,
                'RPAREN': None ,
                'BOOL': None ,
                '\x18': None ,
                'exp': None ,
                'a': None ,
                'b': None ,
                'c': None ,
                'd': None ,
                'e': None ,
                'f': None ,
                'term': None ,
                '\x19': None ,
        },
        'f ::= FORALL PROP ● term': {
                'IFF': None ,
                'IF': None ,
                'OR': None ,
                'XOR': None ,
                'AND': None ,
                'NOT': None ,
                'EXISTS': None ,
                'PROP': 'term ::= PROP ● ',
                'FORALL': None ,
                'LPAREN': 'term ::= LPAREN ● exp RPAREN',
                'RPAREN': None ,
                'BOOL': 'term ::= BOOL ● ',
                '\x18': None ,
                'exp': None ,
                'a': None ,
                'b': None ,
                'c': None ,
                'd': None ,
                'e': None ,
                'f': None ,
                'term': 'f ::= FORALL PROP term ● ',
                '\x19': None ,
        },
        'f ::= FORALL PROP term ● ': {
                'IFF': None ,
                'IF': None ,
                'OR': None ,
                'XOR': None ,
                'AND': None ,
                'NOT': None ,
                'EXISTS': None ,
                'PROP': None ,
                'FORALL': None ,
                'LPAREN': None ,
                'RPAREN': ('f', 3) ,
                'BOOL': None ,
                '\x18': ('f', 3) ,
                'exp': None ,
                'a': None ,
                'b': None ,
                'c': None ,
                'd': None ,
                'e': None ,
                'f': None ,
                'term': None ,
                '\x19': None ,
        },
        'term ::= BOOL ● ': {
                'IFF': ('term', 1) ,
                'IF': ('term', 1) ,
                'OR': ('term', 1) ,
                'XOR': ('term', 1) ,
                'AND': ('term', 1) ,
                'NOT': None ,
                'EXISTS': None ,
                'PROP': None ,
                'FORALL': None ,
                'LPAREN': None ,
                'RPAREN': ('term', 1) ,
                'BOOL': None ,
                '\x18': ('term', 1) ,
                'exp': None ,
                'a': None ,
                'b': None ,
                'c': None ,
                'd': None ,
                'e': None ,
                'f': None ,
                'term': None ,
                '\x19': None ,
        },
}
parse.start = list(parse.table.keys())[0]

# print("{")
# for x in parse.table:
#         print('\t\''+x+'\': {')
#         for y in parse.table[x]:
#                 if isinstance(parse.table[x][y],str): print('\t\t\''+y+'\': \''+parse.table[x][y]+'\',')
#                 else: print('\t\t\''+y+'\':',parse.table[x][y],',')
#         print('\t},')
# print("}")
